services:
  report1:
    build: ./
    command: java -Dspring.profiles.active=dev -jar app.jar
    container_name: report1
    ports:
      - "8080:8080"
    environment:
      WILDBERRIES_TOKEN: "${WILDBERRIES_TOKEN}"
      PORT: 8080

  report2:
    build: ./
    command: java -Dspring.profiles.active=dev -jar app.jar
    container_name: report2
    ports:
      - "8081:8081"
    environment:
      WILDBERRIES_TOKEN: "${WILDBERRIES_TOKEN}"
      PORT: 8081
